apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: telegram-keyword-bot
resources:
  - namespace.yaml
  - configmap.yaml
  - app-pvc.yaml
  - redis.yaml
  - deployment.yaml
  - service.yaml
  - pdb.yaml
  - hpa.yaml
