apiVersion: v1
kind: Secret
metadata:
  name: telegram-keyword-bot-secret
type: Opaque
stringData:
  TELEGRAM_BOT_TOKEN: "REPLACE_ME"
  API_ID: "REPLACE_ME"
  API_HASH: "REPLACE_ME"
  SESSION_STRING: "REPLACE_ME"
  ORACLE_USER: "REPLACE_ME"
  ORACLE_PASSWORD: "REPLACE_ME"
  ORACLE_CONNECT_STRING: "REPLACE_ME"
