apiVersion: v1
kind: Service
metadata:
  name: telegram-keyword-bot
spec:
  selector:
    app: telegram-keyword-bot
  ports:
    - name: http
      port: 3000
      targetPort: http
  type: ClusterIP
